// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeurqhybczvtrmqconhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldXJxaHliY3p2dHJtcWNvbmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjQyMjUsImV4cCI6MjA2ODk0MDIyNX0.WAd1zIjnw3_d6R_O0SaY-U4cjhN1EN1zi9u5yeETLxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});